name: TMI_Multi
channels:
  - defaults
dependencies:
  - aom=3.12.1=ha237518_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - dav1d=1.2.1=h80987f9_0
  - expat=2.7.3=h50f4ffc_4
  - filelock=3.20.0=py312hca03da5_0
  - fontconfig=2.15.0=h29935d0_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - fsspec=2025.10.0=py312h7eb115d_0
  - gettext=0.21.0=hbdbcc25_2
  - giflib=5.2.2=h80987f9_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.2=py312hbcc4bda_0
  - graphite2=1.3.14=hc377ac9_1
  - harfbuzz=10.2.0=he637ebf_1
  - icu=73.1=h313beb8_0
  - importlib-metadata=8.7.0=py312hca03da5_0
  - jinja2=3.1.6=py312hca03da5_0
  - jpeg=9f=h2f69dba_0
  - lcms2=2.17=h7418793_0
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250127.0=cxx17_h313beb8_0
  - libavif=1.3.0=h839b4eb_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libgfortran5=15.2.0=hb654fa1_1
  - libglib=2.84.4=h7a3292d_0
  - libiconv=1.16=h80987f9_3
  - libopenblas=0.3.30=hf2bb037_2
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.50=h5c318fc_0
  - libprotobuf=5.29.3=h14f15fd_1
  - libtiff=4.7.1=h367c460_0
  - libtorch=2.5.1=gpu_mps_h7b1bc93_204
  - libuv=1.48.0=h80987f9_0
  - libwebp-base=1.6.0=h92b2d59_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py312h80987f9_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py312hca03da5_0
  - ncurses=6.5=hee39554_0
  - networkx=3.6.1=py312hca03da5_0
  - nomkl=3.0=0
  - numpy=2.3.5=py312h4bb6f22_0
  - numpy-base=2.3.5=py312h23175f9_0
  - openssl=3.0.18=h9b4081a_0
  - opentelemetry-api=1.38.0=py312hca03da5_0
  - pcre2=10.46=h1dacb4a_0
  - pillow=12.0.0=py312he2d6fe4_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - python=3.12.12=h2bfc596_1
  - pytorch=2.5.1=gpu_mps_py312hbd1d365_204
  - pyyaml=6.0.3=py312h091b9d3_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py312hca03da5_0
  - sleef=3.5.1=h80987f9_2
  - sqlite=3.51.0=hab6afd1_0
  - sympy=1.14.0=py312hca03da5_1
  - tk=8.6.15=hcd8a7d5_0
  - torchvision=0.20.1=mps_py312h620d032_102
  - tqdm=4.67.1=py312h7eb115d_1
  - typing-extensions=4.15.0=py312hca03da5_0
  - typing_extensions=4.15.0=py312hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py312hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zipp=3.23.0=py312hca03da5_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - appnope==0.1.4
      - asttokens==3.0.1
      - attrs==25.4.0
      - backcall==0.2.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - decorator==5.2.1
      - defusedxml==0.7.1
      - docopt==0.6.2
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - idna==3.11
      - ipython==8.12.3
      - jedi==0.19.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.7.0
      - jupyter-core==5.9.1
      - jupyterlab-pygments==0.3.0
      - matplotlib-inline==0.2.1
      - mistune==3.1.4
      - nbclient==0.10.3
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - packaging==25.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - platformdirs==4.5.1
      - prompt-toolkit==3.0.52
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - pyzmq==27.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.30.0
      - six==1.17.0
      - soupsieve==2.8.1
      - stack-data==0.6.3
      - tinycss2==1.4.0
      - tornado==6.5.4
      - traitlets==5.14.3
      - urllib3==2.6.2
      - wcwidth==0.2.14
      - webencodings==0.5.1
      - yarg==0.1.9
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/TMI_Multi
